{"name":"createduplicateuser","status":"failed","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"expected [New User User43 created Successfully] but found [User already exist!]","trace":"java.lang.AssertionError: expected [New User User43 created Successfully] but found [User already exist!]\r\n\tat org.testng.Assert.fail(Assert.java:94)\r\n\tat org.testng.Assert.failNotEquals(Assert.java:513)\r\n\tat org.testng.Assert.assertEqualsImpl(Assert.java:135)\r\n\tat org.testng.Assert.assertEquals(Assert.java:116)\r\n\tat org.testng.Assert.assertEquals(Assert.java:190)\r\n\tat org.testng.Assert.assertEquals(Assert.java:200)\r\n\tat com.enhanzedadmin.qa.pages.CreateUser.createduplicateUser(CreateUser.java:191)\r\n\tat com.enhanzedadmin.qa.testcases.ManageUserTest.createduplicateuser(ManageUserTest.java:201)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)\r\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)\r\n\tat java.lang.reflect.Method.invoke(Unknown Source)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:782)\r\n\tat org.testng.TestRunner.run(TestRunner.java:632)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:366)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:268)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1169)\r\n\tat org.testng.TestNG.run(TestNG.java:1064)\r\n\tat org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)\r\n\tat org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)\r\n\tat org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)\r\n"},"stage":"finished","description":"To check for create user","steps":[],"attachments":[],"parameters":[{"name":"arg3","value":"test"},{"name":"arg2","value":"1.2345678E7"},{"name":"arg1","value":"user43@email.com"},{"name":"arg0","value":"User43"}],"start":1578401056015,"stop":1578401070705,"uuid":"14392cc1-b501-4cfb-a66a-9f9acc7d0441","historyId":"fd74eeaba3b437a409efbd397e52b157","fullName":"com.enhanzedadmin.qa.testcases.ManageUserTest.createduplicateuser","labels":[{"name":"package","value":"com.enhanzedadmin.qa.testcases.ManageUserTest"},{"name":"testClass","value":"com.enhanzedadmin.qa.testcases.ManageUserTest"},{"name":"testMethod","value":"createduplicateuser"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"com.enhanzedadmin.qa.testcases.ManageUserTest"},{"name":"host","value":"DESKTOP-UQCRR3T"},{"name":"thread","value":"4116@DESKTOP-UQCRR3T.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"severity","value":"critical"}],"links":[]}